name: GitHub Releases Backup

on:
  schedule:
    - cron: '0 2 * * 0'  # Her Pazar 02:00
  workflow_dispatch:  # Manuel calistirma

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Create backup
      run: |
        DATE=$(date +%Y%m%d-%H%M%S)
        zip -r backup-$DATE.zip . -x ".git/*" "node_modules/*" "dist/*"
        echo "BACKUP_FILE=backup-$DATE.zip" >> $GITHUB_ENV
        echo "BACKUP_DATE=$DATE" >> $GITHUB_ENV
        
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: backup-${{ env.BACKUP_DATE }}
        release_name: Backup ${{ env.BACKUP_DATE }}
        body: |
          Otomatik proje backupi
          📅 Tarih: ${{ env.BACKUP_DATE }}
          🗂️ Dosya: ${{ env.BACKUP_FILE }}
        draft: false
        prerelease: false
        
    - name: Upload backup
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ env.BACKUP_FILE }}
        asset_name: ${{ env.BACKUP_FILE }}
        asset_content_type: application/zip
