name: GitHub Releases Backup

on:
  schedule:
    - cron: '0 2 * * 0'  # Her Pazar 02:00
  workflow_dispatch:  # Manuel calistirma

jobs:
  backup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    
    - name: Create backup
      run: |
        DATE=$(date +%Y%m%d-%H%M%S)
        zip -r backup-$DATE.zip . -x ".git/*" "node_modules/*" "dist/*"
        echo "BACKUP_FILE=backup-$DATE.zip" >> $GITHUB_ENV
        echo "BACKUP_DATE=$DATE" >> $GITHUB_ENV
        
    - name: Create Release and Upload
      run: |
        gh release create backup-${{ env.BACKUP_DATE }} \
          --title "Backup ${{ env.BACKUP_DATE }}" \
          --notes "Otomatik proje backupi 📅 Tarih: ${{ env.BACKUP_DATE }}" \
          ${{ env.BACKUP_FILE }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Delete old releases
      run: |
        gh release list --limit 100 --json tagName --jq '.[].tagName' | grep "^backup-" | tail -n +3 | xargs -r -I {} gh release delete {} --yes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
