name: Google Drive Backup

on:
  schedule:
    - cron: '0 2 * * 0'  # Her Pazar 02:00
  workflow_dispatch:  # Manuel çalıştırma

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Create backup zip
      run: |
        zip -r backup-$(date +%Y%m%d).zip . -x ".git/*" "node_modules/*" "dist/*"
        
    - name: Upload to Google Drive
      uses: wei/rclone@v1
      env:
        RCLONE_CONFIG_DRIVE_TYPE: drive
        RCLONE_CONFIG_DRIVE_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
      with:
        args: copy backup-*.zip drive:Firebase-Backups/
